site_name: FastAPI CRUD Router
repo_url: https://github.com/awtkns/fastapi-crudrouter
repo_name: awtkns/fastapi-crudrouter
edit_uri: ''

theme:
  name: material
  palette:
    - scheme: primary
      accent: amber
  icon:
    repo: fontawesome/brands/github-alt
    logo: octicons/zap-24
  favicon: assets/zap.svg
  language: en

# Nav
nav:
- Overview: index.md
- Generated Routes: routing.md
- Overriding Routes: overrides.md
- Backends:
    - In Memory: backends/memory.md
    - SQLAlchemy: backends/sqlalchemy.md
    - Databases (async): backends/async.md

google_analytics:
  - UA-186315536-1
  - auto

markdown_extensions:
  - extra
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/awtkns/fastapi-crudrouter
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/adam-watkins-yvr/
  - icon: fontawesome/solid/globe
    link: https://wtkns.dev

extra_css:
  - css/main.css
  - css/termynal.css
extra_javascript:
  - js/termynal.js